apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: modelserver-nov27-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelserver-nov27-2 
  name: modelserver-nov27-2
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: modelserver-nov27-2 
